name: Build Docker Image
on:
  push:
    tags:
      - '*'

env:
  DOCKER_IMAGE_NAME: remote-forward-ssh-client

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Image Tag
        run: |
          echo "DOCKER_IMAGE_TAG=${GITHUB_REF##*/}" >> ${GITHUB_ENV}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ARM向けのDockerImageを作成するための下準備 01
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # ARM向けのDockerImageを作成するための下準備 02
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: |
            ghcr.io/takahiro55555/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
            ghcr.io/takahiro55555/${{ env.DOCKER_IMAGE_NAME }}:latest
