name: Check Vulnerability
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * 1'
env:
  DOCKER_IMAGE_NAME: remote-forward-ssh-client
  DOCKER_IMAGE_TAG: latest

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/takahiro55555/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Create an Issue
        if: failure()
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { GITHUB_SERVER_URL, GITHUB_REPOSITORY, GITHUB_RUN_ID } = process.env
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Dockerイメージに脆弱性が発見されました',
              body: `詳細: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}`,
            })
